### PR TITLE
feat: added screenshot in readme

### PR DESCRIPTION
**Pull request by muthukumarimoorthi**
before i do screenshot there is no screenshot so I do that app.

### CODE REVIEW

**Comment by anburocky3** [comment]
Put screenshots in this location `screenshots` folder and modify the readme file

**Comment by muthukumarimoorthi** [comment]
okey @anburocky3

**Comment by muthukumarimoorthi** [comment]
modified screenshots location images to screenshots @anburocky3

**Review by anburocky3 — APPROVED** [review]
Hopefully it's OK.

**Pull request merged**
